# Generated by Django 4.2.15 on 2024-08-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=255)),
                ('image', models.URLField(default='')),
                ('preview_images', models.URLField(default='')),
                ('size_prices', models.CharField(default='0', max_length=10)),
                ('sizes', models.CharField(max_length=4, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=4)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
