# Generated by Django 5.0.4 on 2024-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
