# Generated by Django 4.2.11 on 2024-05-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0005_productcolors_delete_shopproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductColors',
            new_name='ProductColor',
        ),
    ]
