# Generated by Django 4.2.11 on 2024-05-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0007_productvariant_delete_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('size', models.CharField(max_length=4)),
                ('colors', models.ManyToManyField(to='merch_shop.color')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('stripe_price_id', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=4)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch_shop.color')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
