# Generated by Django 4.2.11 on 2024-05-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0009_price_remove_product_product_id_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='merch_shop.product'),
            preserve_default=False,
        ),
    ]
