# Generated by Django 4.2.11 on 2024-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0012_product_description_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(default=None, null=True, to='merch_shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
