# Generated by Django 4.2.11 on 2024-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0013_alter_product_colors_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
