# Generated by Django 4.2.11 on 2024-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0017_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
