# Generated by Django 4.2.11 on 2024-05-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0018_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_images',
            field=models.URLField(default=''),
        ),
    ]
